In [ ]:

# In mxnet

In [1]:

import mxnet as mx
from mxnet import autograd

with autograd.record():
    x = mx.random.randn(2, 2)
    x.attach_grad()

    y = x ** 2
    y.attach_grad()

    z = y.mean()
    print(f"{x} - {y}")

print(f"{type(x)} -> {type(y)}")

print(f"{x.grad} -> {y.grad}")

z.backward()

print(f"{x.grad} -> {y.grad}")
print(f"{x / 2}")


[[2.2122064 0.7740038]
 [1.0434403 1.1839255]]
<NDArray 2x2 @cpu(0)> - 
[[4.893857  0.5990819]
 [1.0887678 1.4016796]]
<NDArray 2x2 @cpu(0)>
<class 'mxnet.ndarray.ndarray.NDArray'> -> <class 'mxnet.ndarray.ndarray.NDArray'>

[[0. 0.]
 [0. 0.]]
<NDArray 2x2 @cpu(0)> -> 
[[0. 0.]
 [0. 0.]]
<NDArray 2x2 @cpu(0)>

[[0. 0.]
 [0. 0.]]
<NDArray 2x2 @cpu(0)> -> 
[[0.25 0.25]
 [0.25 0.25]]
<NDArray 2x2 @cpu(0)>

[[1.1061032  0.3870019 ]
 [0.5217202  0.59196275]]
<NDArray 2x2 @cpu(0)>


In [ ]:

# In torch

In [4]:

import torch as tt

x = tt.randn(2, 2, requires_grad=True)

y = x ** 2

z = y.mean()

print(f"{type(x)} -> {type(y)}")

print(f"{x.grad} -> {y.grad}")

z.backward()

print(f"{x.grad} -> {y.grad}")
print(f"{x / 2}")

<class 'torch.Tensor'> -> <class 'torch.Tensor'>
None -> None
tensor([[ 1.0038,  0.3119],
        [-1.0436, -0.4164]]) -> None
tensor([[ 1.0038,  0.3119],
        [-1.0436, -0.4164]], grad_fn=<DivBackward0>)
