In [15]:
from torch import nn
import torch

from torch.nn import functional as ff

In [8]:
loss = nn.CrossEntropyLoss()
input = torch.randn((3, 5), requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
print(input)
print(target)
print(output)

tensor([[ 1.1697,  1.3291, -0.9306, -1.1790,  1.5958],
        [-1.3248,  1.0758, -1.7669, -1.5140,  0.6727],
        [-0.6522, -0.9713,  0.2155,  2.1093,  0.8517]], requires_grad=True)
tensor([2, 2, 4])
tensor(2.8798, grad_fn=<NllLossBackward>)


In [24]:

batchN = 4

lossFn = nn.NLLLoss(reduction="none")
feature = torch.rand((batchN, 3, 5, 5), dtype=torch.float32)
dist = ff.softmax(feature, dim=1)

target = torch.ones((batchN, 5, 5), dtype=torch.long)

loss = lossFn(dist, target)
loss

tensor([[[-0.3040, -0.3641, -0.4490, -0.1982, -0.2875],
         [-0.4909, -0.2620, -0.5104, -0.4663, -0.3869],
         [-0.3263, -0.3395, -0.2699, -0.2584, -0.3948],
         [-0.3768, -0.2952, -0.3208, -0.4913, -0.5319],
         [-0.3129, -0.2824, -0.2622, -0.3194, -0.3036]],

        [[-0.2907, -0.3649, -0.3824, -0.4044, -0.2347],
         [-0.2743, -0.3892, -0.3323, -0.3030, -0.2838],
         [-0.2525, -0.2815, -0.3275, -0.2894, -0.3100],
         [-0.3690, -0.2300, -0.2597, -0.4275, -0.2786],
         [-0.3133, -0.3279, -0.2537, -0.4160, -0.2633]],

        [[-0.2798, -0.3412, -0.2755, -0.4009, -0.4727],
         [-0.2650, -0.4413, -0.3598, -0.3886, -0.3740],
         [-0.2510, -0.4740, -0.2704, -0.2659, -0.3620],
         [-0.3207, -0.2804, -0.5051, -0.3747, -0.3036],
         [-0.3126, -0.3552, -0.4062, -0.4940, -0.2779]],

        [[-0.3258, -0.2760, -0.3978, -0.3426, -0.3073],
         [-0.4276, -0.3313, -0.2331, -0.3047, -0.2542],
         [-0.3409, -0.2510, -0.3120, -0.26

In [23]:

batchN = 4

lossFn = nn.NLLLoss(reduction="none")

feature = torch.zeros((batchN, 5), dtype=torch.float32)
feature[:, 0] = torch.ones(batchN) * 4

print(feature)

dist = ff.softmax(feature, dim=1)

print(dist)

target = torch.zeros((batchN), dtype=torch.long)

loss = lossFn(dist, target)
loss

tensor([[4., 0., 0., 0., 0.],
        [4., 0., 0., 0., 0.],
        [4., 0., 0., 0., 0.],
        [4., 0., 0., 0., 0.]])
tensor([[0.9317, 0.0171, 0.0171, 0.0171, 0.0171],
        [0.9317, 0.0171, 0.0171, 0.0171, 0.0171],
        [0.9317, 0.0171, 0.0171, 0.0171, 0.0171],
        [0.9317, 0.0171, 0.0171, 0.0171, 0.0171]])


tensor([-0.9317, -0.9317, -0.9317, -0.9317])